version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: Asia/Jakarta
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_bin"
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot_pass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - zbx

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.4-latest
    container_name: zabbix-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
      ZBX_DEBUGLEVEL: 3
      TZ: Asia/Jakarta
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zbx

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.4-latest
    container_name: zabbix-web
    depends_on:
      zabbix-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Jakarta
    ports:
      - "80:8080"
    networks:
      - zbx

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-7.4-latest
    container_name: zabbix-agent
    depends_on:
      zabbix-server:
        condition: service_started
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: "docker-zabbix-agent"
      TZ: Asia/Jakarta
    networks:
      - zbx

volumes:
  mysql_data:
  zabbix_server_data:

networks:
  zbx:
    driver: bridge
