services:
  zabbix-server:
    container_name: zabbix-server
    image: allworldit/zabbix:latest
    hostname: zabbix-server
    environment:
      - ZABBIX_MODE=server
      - ZABBIX_DATABASE_TYPE=timescaledb
      - ZABBIX_ADMIN_USERNAME=Admin
      - ZABBIX_ADMIN_PASSWORD=testtest
      - ZABBIX_SERVER_WEBSERVICE_URL=http://zabbix-webservice:10053/report
      - POSTGRES_HOST=postgresql
      - POSTGRES_DATABASE=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.10
        ipv6_address: 64:ff9b:1::10:10

  zabbix-frontend:
    container_name: zabbix-frontend
    image: allworldit/zabbix:latest
    environment:
      ZABBIX_MODE: frontend
      ZABBIX_DATABASE_TYPE: postgresql
      POSTGRES_HOST: postgresql
      POSTGRES_DATABASE: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: dbpassword
      NGINX_SET_REAL_IP_FROM: |
        172.16.0.0/12
        64:ff9b:1::/96
    ports:
      - "8080:80"
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.20
        ipv6_address: 64:ff9b:1::10:20

  zabbix-webservice:
    container_name: zabbix-webservice
    image: allworldit/zabbix:latest
    extra_hosts:
      - "zabbix.frontend.example.com:172.16.0.1"
    environment:
      - ZABBIX_MODE=webservice
      - ZABBIX_WEBSERVICE_ALLOWEDIP=zabbix-server
    networks:
      internal:
      external:
        ipv4_address: 172.16.10.30
        ipv6_address: 64:ff9b:1::10:30

  zabbix-postgresql:
    container_name: zabbix-postgresql
    image: registry.conarx.tech/containers/postgresql-timescaledb
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DATABASE=zabbix
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    enable_ipv6: true
    internal: true
  external:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker1
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
        - subnet: 64:ff9b:1::10:0/112
