version: "3.9"

services:
  zabbix-server:
    image: allworldit/zabbix:latest
    hostname: zabbix-server
    environment:
      - ZABBIX_MODE=server
      - ZABBIX_DATABASE_TYPE=timescaledb
      - ZABBIX_ADMIN_USERNAME=Admin
      - ZABBIX_ADMIN_PASSWORD=testtest
      - ZABBIX_SERVER_WEBSERVICE_URL=http://zabbix-webservice:10053/report
      - POSTGRES_HOST=postgresql
      - POSTGRES_DATABASE=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
    networks:
      - zabbix-networks

  zabbix-frontend:
    image: allworldit/zabbix:latest
    environment:
      - ZABBIX_MODE=frontend
      - ZABBIX_DATABASE_TYPE=postgresql
      - POSTGRES_HOST=postgresql
      - POSTGRES_DATABASE=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - "8080:80"
    networks:
      - zabbix-networks

  zabbix-webservice:
    image: allworldit/zabbix:latest
    extra_hosts:
      - "zabbix.frontend.example.com:172.16.0.1"
    environment:
      - ZABBIX_MODE=webservice
      - ZABBIX_WEBSERVICE_ALLOWEDIP=zabbix-server
    networks:
      - zabbix-networks

  postgresql:
    image: registry.conarx.tech/containers/postgresql-timescaledb
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DATABASE=zabbix
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    networks:
      - zabbix-networks

networks:
  zabbix-networks:
    driver: bridge
    internal: true
