services:
  mysql-zabbix:
    image: mysql:8.0.36
    container_name: mysql-zabbix
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot_pass || exit 1"]
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 10s
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: Asia/Jakarta
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix_network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.0.4
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_DATABASE: zabbix
      ZBX_DEBUGLEVEL: 3
      TZ: Asia/Jakarta
    depends_on:
      mysql-zabbix:
        condition: service_healthy
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix_network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.0.4
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Jakarta
    ports:
      - "9090:8080"
    depends_on:
      zabbix-server:
        condition: service_started
    restart: unless-stopped
    networks:
      - zabbix_network

volumes:
  mysql_data:

networks:
  zabbix_network:
    driver: bridge
    name: zabbix_network
