services:
  zabbix-allinone:
    image: avgurx/zabbix:latest
    container_name: zabbix
    ports:
      - "8080:80"
      - "10051:10051"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - ZBX_SERVER_NAME=Zabbix Server
      - PHP_TZ=Asia/Jakarta
    restart: unless-stopped
    networks:
      - zbx-net

networks:
  zbx-net:
    driver: bridge
